version: '3.8'

services:
   # db
   db: 
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-appsDB8}
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

   # phpmyadmin
   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: ${PLATFORM}
    container_name: ${PMA_CONTAINER_NAME:-phpmyadmin}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PMA_PORT:-8081}:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 1G
    networks:
      - mysql_network

#volumes
volumes:
  mysql_data:
    driver: local

#network
networks:
  mysql_network:
   driver: bridge
