version: '3.8'

services:
   # db
   db: 
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-appsDB}
    restart: unless-stopped
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    networks:
      - mysql_network

   # phpmyadmin
   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: ${PMA_CONTAINER_NAME:-phpmyadmin}
    restart: unless-stopped
    ports:
      - '${PHPMYADMIN_PORT:-8081}:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 1G
    depends_on:
      - db
    networks:
      - mysql_network

#volumes
volumes:
  mysql_data:
    driver: local

#network
networks:
  mysql_network:
   driver: bridge